name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: golang:1.25-trixie

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: archiver_test
          POSTGRES_USER: temba
          POSTGRES_PASSWORD: temba
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Run tests
      run: go test -p=1 -coverprofile=coverage.text -covermode=atomic ./...
      env:
        DATABASE_URL: postgres://temba:temba@postgres:5432/archiver_test?sslmode=disable&TimeZone=UTC
        ARCHIVER_AWS_ACCESS_KEY_ID: ${{ secrets.ARCHIVER_AWS_ACCESS_KEY_ID }}
        ARCHIVER_AWS_SECRET_ACCESS_KEY: ${{ secrets.ARCHIVER_AWS_SECRET_ACCESS_KEY }}

    - name: Upload coverage
      if: success()
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
